# This is a basic workflow that is manually triggered

name: Update dependency

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      dependency_repo:
       type: text
       required: true
       default: JeanBarriere/gh-action-build-and-release
       description: The dependency repository


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  fetch-dependency:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v3
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        path: main
    - name: Checkout dependency
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.dependency_repo }}
        path: dependency
        ref: main
    - name: copy dependency file
      run: |
        cp dependency/version.json main/modules/action-build-release.json
        ls main/modules
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "chore: update dependency"
        title: Update Dependency
        body: Update dependency to reflect new release
        branch: chore/update-dependency
        path: main
