# This is a basic workflow that is manually triggered

name: Update dependency

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      dependency_repo:
       type: text
       required: true
       default: JeanBarriere/gh-action-build-and-release
       description: The dependency repository


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  fetch-dependency:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v3
    - name: clone dependency repository
      run: |
        git clone https://.:${{ GITHUB_TOKEN }}@github.com/${{ github.event.inputs.dependency_repo }} _tmp_dep
    - name: copy dependency file
      run: |
        cp _tmp_dep/version.json modules/action-build-release.json
    - name: remove dependency repository
      run: |
        rm -rf _tmp_dep
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "chore: update dependency"
        title: Update Dependency
        body: Update dependency to reflect new release
        branch: chore/update-dependency
        base: main
        
